sonar.projectKey=achillemonod_labobeton:client
sonar.projectName=LaboBeton - Client
sonar.organization=achillemonod
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/build/**,**/public/**,**/*.test.js,**/github/**,**/__tests__/**

# coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

