# Projet parent
sonar.projectKey=achillemonod_labobeton
sonar.projectName=LaboBeton
sonar.organization=achillemonod
sonar.modules=client,server

# Configuration du module client
achillemonod_labobeton:client.sonar.projectKey=achillemonod_labobeton:client
achillemonod_labobeton:client.sonar.projectName=LaboBeton - Client
achillemonod_labobeton:client.sonar.sources=client/src
achillemonod_labobeton:client.sonar.javascript.lcov.reportPaths=client/coverage/lcov.info
achillemonod_labobeton:client.sonar.exclusions=**/node_modules/**,**/build/**,**/public/**,**/*.test.js,**/github/**,**/__tests__/**

# Configuration du module server
achillemonod_labobeton:server.sonar.projectKey=achillemonod_labobeton:server
achillemonod_labobeton:server.sonar.projectName=LaboBeton - Server
achillemonod_labobeton:server.sonar.sources=server


