# Projet parent
sonar.projectKey=AchilleMonod_LaboBeton
sonar.projectName=LaboBeton
sonar.organization=achillemonod
sonar.modules=client,server

# Configuration du module client
AchilleMonod_LaboBeton:client.sonar.projectKey=achillemonod_labobeton:client
AchilleMonod_LaboBeton:client.sonar.projectName=LaboBeton - Client
AchilleMonod_LaboBeton:client.sonar.sources=client/src
AchilleMonod_LaboBeton:client.sonar.javascript.lcov.reportPaths=client/coverage/lcov.info
AchilleMonod_LaboBeton:client.sonar.exclusions=**/node_modules/**,**/build/**,**/public/**,**/*.test.js,**/github/**,**/__tests__/**

# Configuration du module server
AchilleMonod_LaboBeton:server.sonar.projectKey=achillemonod_labobeton:server
AchilleMonod_LaboBeton:server.sonar.projectName=LaboBeton - Server
AchilleMonod_LaboBeton:server.sonar.sources=server


