# Projet parent
sonar.projectKey=achillemonod_labobeton
sonar.projectName=LaboBeton
sonar.organization=achillemonod
sonar.modules=client,server

# Configuration du module "client"
client.sonar.projectKey=achillemonod_labobeton:client
client.sonar.projectName=LaboBeton - Client
client.sonar.sources=client/src
client.sonar.javascript.lcov.reportPaths=client/coverage/lcov.info

# Configuration du module "server"
server.sonar.projectKey=achillemonod_labobeton:server
server.sonar.projectName=LaboBeton - Server
server.sonar.sources=server

