sonar.projectKey=achillemonod_labobeton:server
sonar.projectName=LaboBeton - Server
sonar.organization=achillemonod
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/build/**,**/public/**,**/*.test.js


